name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - uses: actions/checkout@v4
      with:
        repository: netdata/netdata
        path: netdata
    - uses: actions/checkout@v4
    - name: install dependencies
      run: |
        sudo apt update -qq
        sudo apt install -qq libupsclient-dev
    - name: make
      run: clang -Wall -Inetdata/src main.c -lupsclient
