name: C/C++ CI

on:
  push:
    branches: ["main"]
  pull_request:
    branches: ["main"]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - name: install dependencies
        run: |
          sudo apt update -qq
          sudo apt install -qq libupsclient-dev
          sudo netdata-*/packaging/installer/install-required-packages.sh --dont-wait --non-interactive netdata
      - name: build
        run: |
          cmake -B build
          cmake --build build --target upsd.plugin
