name: C/C++ CI

on:
  push:
  pull_request:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
    - name: Checkout netdata-plugin-upsd
      uses: actions/checkout@v4

    - name: Checkout netdata/netdata
      uses: actions/checkout@v4
      with:
        repository: netdata/netdata
        path: netdata
        submodules: recursive

    - name: Install netdata's dependencies
      run: >
        exec netdata/packaging/installer/install-required-packages.sh 
          --dont-wait
          --non-interactive

    - name: Build netdata
      run: sudo bash ./netdata-installer.sh --dont-start-it --disable-go
      working-directory: netdata

    - name: install netdata-plugin-upsd's dependencies
      run: |
        sudo apt update -qq
        sudo apt install -qq libupsclient-dev

    - name: make
      run: clang -Wall -Inetdata/src main.c -lupsclient